name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x BudgetBee/gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug
        working-directory: BudgetBee

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest
        working-directory: BudgetBee

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: BudgetBee/app/build/outputs/apk/debug/app-debug.apk
